[program:apiwhatsapp-scheduler]
process_name=%(program_name)s
command=php /var/www/apiwhatsapp/artisan schedule:work
directory=/var/www/apiwhatsapp
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/apiwhatsapp-scheduler.log
stopwaitsecs=60
