[program:apiwhatsapp-webhooks-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/apiwhatsapp/artisan queue:work redis --queue=webhooks,outgoing-webhooks --sleep=1 --tries=5 --backoff=10 --timeout=120 --memory=256
directory=/var/www/apiwhatsapp
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/apiwhatsapp-webhooks-worker.log
stopwaitsecs=180
